#! /usr/bin/python3

import os
import random
import time
import sys

if len(sys.argv)!=2:
    print("Invalid args count!")
    os._exit(1)

parent_pid=os.getpid()
children_count=int(sys.argv[1])

for i in range(children_count):
    status=os.fork()
    if status!=0:
        res=f'Parent[{parent_pid}]: I run children process with PID {status}'
        print(res)
    else:
        args=["./child", str(random.randint(5, 10))]
        os.execve("./child", args, os.environ)

while children_count > 0:
    status=os.wait()
    res=f'Parent[{parent_pid}]: Child with PID {status[0]} terminated. Exit Status {status[1]}.'
    print(res)
    if status[1]==0:
        children_count-=1
    else:
        new_child_status=os.fork()
        if new_child_status==0:
            args = ["./child", str(random.randint(5, 10))]
            os.execve("./child", args, os.environ)
