#! /usr/bin/python3

import random
import time

operators = ['/', '*', '-', '+']
n = random.randint(120, 180)

for i in range(n):
    x = random.randint(1, 9)
    o = random.choice(operators)
    y = random.randint(1, 9)
    print(f'{x} {o} {y}', flush=True)
    time.sleep(1)
